// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.

package store

import (
	"time"

	"github.com/jryannel/sqlb"
)

type accountLockColumns struct {
	UserID   sqlb.Col[string]
	LockedAt sqlb.Col[time.Time]
}

// AccountLockCols are the typed columns of account_locks.
var AccountLockCols = accountLockColumns{
	UserID:   sqlb.Typed[string]("user_id"),
	LockedAt: sqlb.Typed[time.Time]("locked_at"),
}

// AccountLockUpdate is a typed update statement for account_locks.
type AccountLockUpdate struct {
	stmt *sqlb.Update[AccountLock]
}

// UpdateAccountLock starts a typed update.
func UpdateAccountLock() *AccountLockUpdate {
	return &AccountLockUpdate{stmt: sqlb.UpdateRows[AccountLock]()}
}

// SetLockedAt sets locked_at.
func (u *AccountLockUpdate) SetLockedAt(v time.Time) *AccountLockUpdate {
	u.stmt.Set("locked_at", v)
	return u
}

// Where narrows the affected rows.
func (u *AccountLockUpdate) Where(preds ...sqlb.Pred) *AccountLockUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *AccountLockUpdate) Stmt() *sqlb.Update[AccountLock] { return u.stmt }

type deviceAuthorizationColumns struct {
	ID              sqlb.Col[string]
	DeviceCodeHash  sqlb.TextCol[string]
	UserCode        sqlb.TextCol[string]
	ClientID        sqlb.TextCol[string]
	Scope           sqlb.TextCol[string]
	Status          sqlb.Col[DeviceAuthorizationStatus]
	UserID          sqlb.Col[string]
	ExpiresAt       sqlb.Col[time.Time]
	IntervalSeconds sqlb.Col[int32]
	LastPolledAt    sqlb.Col[time.Time]
	CreatedAt       sqlb.Col[time.Time]
	UpdatedAt       sqlb.Col[time.Time]
}

// DeviceAuthorizationCols are the typed columns of device_authorizations.
var DeviceAuthorizationCols = deviceAuthorizationColumns{
	ID:              sqlb.Typed[string]("id"),
	DeviceCodeHash:  sqlb.TextColumn[string]("device_code_hash"),
	UserCode:        sqlb.TextColumn[string]("user_code"),
	ClientID:        sqlb.TextColumn[string]("client_id"),
	Scope:           sqlb.TextColumn[string]("scope"),
	Status:          sqlb.Typed[DeviceAuthorizationStatus]("status"),
	UserID:          sqlb.Typed[string]("user_id"),
	ExpiresAt:       sqlb.Typed[time.Time]("expires_at"),
	IntervalSeconds: sqlb.Typed[int32]("interval_seconds"),
	LastPolledAt:    sqlb.Typed[time.Time]("last_polled_at"),
	CreatedAt:       sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:       sqlb.Typed[time.Time]("updated_at"),
}

// DeviceAuthorizationUpdate is a typed update statement for device_authorizations.
type DeviceAuthorizationUpdate struct {
	stmt *sqlb.Update[DeviceAuthorization]
}

// UpdateDeviceAuthorization starts a typed update.
func UpdateDeviceAuthorization() *DeviceAuthorizationUpdate {
	return &DeviceAuthorizationUpdate{stmt: sqlb.UpdateRows[DeviceAuthorization]()}
}

// SetDeviceCodeHash sets device_code_hash.
func (u *DeviceAuthorizationUpdate) SetDeviceCodeHash(v string) *DeviceAuthorizationUpdate {
	u.stmt.Set("device_code_hash", v)
	return u
}

// SetUserCode sets user_code.
func (u *DeviceAuthorizationUpdate) SetUserCode(v string) *DeviceAuthorizationUpdate {
	u.stmt.Set("user_code", v)
	return u
}

// SetClientID sets client_id.
func (u *DeviceAuthorizationUpdate) SetClientID(v string) *DeviceAuthorizationUpdate {
	u.stmt.Set("client_id", v)
	return u
}

// SetScope sets scope.
func (u *DeviceAuthorizationUpdate) SetScope(v string) *DeviceAuthorizationUpdate {
	u.stmt.Set("scope", v)
	return u
}

// SetStatus sets status.
func (u *DeviceAuthorizationUpdate) SetStatus(v DeviceAuthorizationStatus) *DeviceAuthorizationUpdate {
	u.stmt.Set("status", v)
	return u
}

// SetUserID sets user_id.
func (u *DeviceAuthorizationUpdate) SetUserID(v *string) *DeviceAuthorizationUpdate {
	u.stmt.Set("user_id", v)
	return u
}

// SetExpiresAt sets expires_at.
func (u *DeviceAuthorizationUpdate) SetExpiresAt(v time.Time) *DeviceAuthorizationUpdate {
	u.stmt.Set("expires_at", v)
	return u
}

// SetIntervalSeconds sets interval_seconds.
func (u *DeviceAuthorizationUpdate) SetIntervalSeconds(v int32) *DeviceAuthorizationUpdate {
	u.stmt.Set("interval_seconds", v)
	return u
}

// SetLastPolledAt sets last_polled_at.
func (u *DeviceAuthorizationUpdate) SetLastPolledAt(v *time.Time) *DeviceAuthorizationUpdate {
	u.stmt.Set("last_polled_at", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *DeviceAuthorizationUpdate) SetCreatedAt(v time.Time) *DeviceAuthorizationUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *DeviceAuthorizationUpdate) SetUpdatedAt(v time.Time) *DeviceAuthorizationUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *DeviceAuthorizationUpdate) Where(preds ...sqlb.Pred) *DeviceAuthorizationUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *DeviceAuthorizationUpdate) Stmt() *sqlb.Update[DeviceAuthorization] { return u.stmt }

type emailVerificationTokenColumns struct {
	ID        sqlb.Col[string]
	UserID    sqlb.Col[string]
	TokenHash sqlb.TextCol[string]
	ExpiresAt sqlb.Col[time.Time]
	UsedAt    sqlb.Col[time.Time]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// EmailVerificationTokenCols are the typed columns of email_verification_tokens.
var EmailVerificationTokenCols = emailVerificationTokenColumns{
	ID:        sqlb.Typed[string]("id"),
	UserID:    sqlb.Typed[string]("user_id"),
	TokenHash: sqlb.TextColumn[string]("token_hash"),
	ExpiresAt: sqlb.Typed[time.Time]("expires_at"),
	UsedAt:    sqlb.Typed[time.Time]("used_at"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// EmailVerificationTokenUpdate is a typed update statement for email_verification_tokens.
type EmailVerificationTokenUpdate struct {
	stmt *sqlb.Update[EmailVerificationToken]
}

// UpdateEmailVerificationToken starts a typed update.
func UpdateEmailVerificationToken() *EmailVerificationTokenUpdate {
	return &EmailVerificationTokenUpdate{stmt: sqlb.UpdateRows[EmailVerificationToken]()}
}

// SetUserID sets user_id.
func (u *EmailVerificationTokenUpdate) SetUserID(v string) *EmailVerificationTokenUpdate {
	u.stmt.Set("user_id", v)
	return u
}

// SetTokenHash sets token_hash.
func (u *EmailVerificationTokenUpdate) SetTokenHash(v string) *EmailVerificationTokenUpdate {
	u.stmt.Set("token_hash", v)
	return u
}

// SetExpiresAt sets expires_at.
func (u *EmailVerificationTokenUpdate) SetExpiresAt(v time.Time) *EmailVerificationTokenUpdate {
	u.stmt.Set("expires_at", v)
	return u
}

// SetUsedAt sets used_at.
func (u *EmailVerificationTokenUpdate) SetUsedAt(v *time.Time) *EmailVerificationTokenUpdate {
	u.stmt.Set("used_at", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *EmailVerificationTokenUpdate) SetCreatedAt(v time.Time) *EmailVerificationTokenUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *EmailVerificationTokenUpdate) SetUpdatedAt(v time.Time) *EmailVerificationTokenUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *EmailVerificationTokenUpdate) Where(preds ...sqlb.Pred) *EmailVerificationTokenUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *EmailVerificationTokenUpdate) Stmt() *sqlb.Update[EmailVerificationToken] { return u.stmt }

type failedLoginAttemptColumns struct {
	ID        sqlb.Col[string]
	Email     sqlb.TextCol[string]
	IPAddress sqlb.TextCol[string]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// FailedLoginAttemptCols are the typed columns of failed_login_attempts.
var FailedLoginAttemptCols = failedLoginAttemptColumns{
	ID:        sqlb.Typed[string]("id"),
	Email:     sqlb.TextColumn[string]("email"),
	IPAddress: sqlb.TextColumn[string]("ip_address"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// FailedLoginAttemptUpdate is a typed update statement for failed_login_attempts.
type FailedLoginAttemptUpdate struct {
	stmt *sqlb.Update[FailedLoginAttempt]
}

// UpdateFailedLoginAttempt starts a typed update.
func UpdateFailedLoginAttempt() *FailedLoginAttemptUpdate {
	return &FailedLoginAttemptUpdate{stmt: sqlb.UpdateRows[FailedLoginAttempt]()}
}

// SetEmail sets email.
func (u *FailedLoginAttemptUpdate) SetEmail(v string) *FailedLoginAttemptUpdate {
	u.stmt.Set("email", v)
	return u
}

// SetIPAddress sets ip_address.
func (u *FailedLoginAttemptUpdate) SetIPAddress(v string) *FailedLoginAttemptUpdate {
	u.stmt.Set("ip_address", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *FailedLoginAttemptUpdate) SetCreatedAt(v time.Time) *FailedLoginAttemptUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *FailedLoginAttemptUpdate) SetUpdatedAt(v time.Time) *FailedLoginAttemptUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *FailedLoginAttemptUpdate) Where(preds ...sqlb.Pred) *FailedLoginAttemptUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *FailedLoginAttemptUpdate) Stmt() *sqlb.Update[FailedLoginAttempt] { return u.stmt }

type passwordResetTokenColumns struct {
	ID        sqlb.Col[string]
	UserID    sqlb.Col[string]
	TokenHash sqlb.TextCol[string]
	ExpiresAt sqlb.Col[time.Time]
	UsedAt    sqlb.Col[time.Time]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// PasswordResetTokenCols are the typed columns of password_reset_tokens.
var PasswordResetTokenCols = passwordResetTokenColumns{
	ID:        sqlb.Typed[string]("id"),
	UserID:    sqlb.Typed[string]("user_id"),
	TokenHash: sqlb.TextColumn[string]("token_hash"),
	ExpiresAt: sqlb.Typed[time.Time]("expires_at"),
	UsedAt:    sqlb.Typed[time.Time]("used_at"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// PasswordResetTokenUpdate is a typed update statement for password_reset_tokens.
type PasswordResetTokenUpdate struct {
	stmt *sqlb.Update[PasswordResetToken]
}

// UpdatePasswordResetToken starts a typed update.
func UpdatePasswordResetToken() *PasswordResetTokenUpdate {
	return &PasswordResetTokenUpdate{stmt: sqlb.UpdateRows[PasswordResetToken]()}
}

// SetUserID sets user_id.
func (u *PasswordResetTokenUpdate) SetUserID(v string) *PasswordResetTokenUpdate {
	u.stmt.Set("user_id", v)
	return u
}

// SetTokenHash sets token_hash.
func (u *PasswordResetTokenUpdate) SetTokenHash(v string) *PasswordResetTokenUpdate {
	u.stmt.Set("token_hash", v)
	return u
}

// SetExpiresAt sets expires_at.
func (u *PasswordResetTokenUpdate) SetExpiresAt(v time.Time) *PasswordResetTokenUpdate {
	u.stmt.Set("expires_at", v)
	return u
}

// SetUsedAt sets used_at.
func (u *PasswordResetTokenUpdate) SetUsedAt(v *time.Time) *PasswordResetTokenUpdate {
	u.stmt.Set("used_at", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *PasswordResetTokenUpdate) SetCreatedAt(v time.Time) *PasswordResetTokenUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *PasswordResetTokenUpdate) SetUpdatedAt(v time.Time) *PasswordResetTokenUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *PasswordResetTokenUpdate) Where(preds ...sqlb.Pred) *PasswordResetTokenUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *PasswordResetTokenUpdate) Stmt() *sqlb.Update[PasswordResetToken] { return u.stmt }

type pendingTwoFactorSessionColumns struct {
	ID        sqlb.Col[string]
	UserID    sqlb.Col[string]
	TokenHash sqlb.TextCol[string]
	ExpiresAt sqlb.Col[time.Time]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// PendingTwoFactorSessionCols are the typed columns of pending_two_factor_sessions.
var PendingTwoFactorSessionCols = pendingTwoFactorSessionColumns{
	ID:        sqlb.Typed[string]("id"),
	UserID:    sqlb.Typed[string]("user_id"),
	TokenHash: sqlb.TextColumn[string]("token_hash"),
	ExpiresAt: sqlb.Typed[time.Time]("expires_at"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// PendingTwoFactorSessionUpdate is a typed update statement for pending_two_factor_sessions.
type PendingTwoFactorSessionUpdate struct {
	stmt *sqlb.Update[PendingTwoFactorSession]
}

// UpdatePendingTwoFactorSession starts a typed update.
func UpdatePendingTwoFactorSession() *PendingTwoFactorSessionUpdate {
	return &PendingTwoFactorSessionUpdate{stmt: sqlb.UpdateRows[PendingTwoFactorSession]()}
}

// SetUserID sets user_id.
func (u *PendingTwoFactorSessionUpdate) SetUserID(v string) *PendingTwoFactorSessionUpdate {
	u.stmt.Set("user_id", v)
	return u
}

// SetTokenHash sets token_hash.
func (u *PendingTwoFactorSessionUpdate) SetTokenHash(v string) *PendingTwoFactorSessionUpdate {
	u.stmt.Set("token_hash", v)
	return u
}

// SetExpiresAt sets expires_at.
func (u *PendingTwoFactorSessionUpdate) SetExpiresAt(v time.Time) *PendingTwoFactorSessionUpdate {
	u.stmt.Set("expires_at", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *PendingTwoFactorSessionUpdate) SetCreatedAt(v time.Time) *PendingTwoFactorSessionUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *PendingTwoFactorSessionUpdate) SetUpdatedAt(v time.Time) *PendingTwoFactorSessionUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *PendingTwoFactorSessionUpdate) Where(preds ...sqlb.Pred) *PendingTwoFactorSessionUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *PendingTwoFactorSessionUpdate) Stmt() *sqlb.Update[PendingTwoFactorSession] { return u.stmt }

type personalAccessTokenColumns struct {
	ID         sqlb.Col[string]
	UserID     sqlb.Col[string]
	Name       sqlb.TextCol[string]
	TokenHash  sqlb.TextCol[string]
	Scopes     sqlb.ArrayCol[string]
	ExpiresAt  sqlb.Col[time.Time]
	LastUsedAt sqlb.Col[time.Time]
	RevokedAt  sqlb.Col[time.Time]
	CreatedAt  sqlb.Col[time.Time]
	UpdatedAt  sqlb.Col[time.Time]
}

// PersonalAccessTokenCols are the typed columns of personal_access_tokens.
var PersonalAccessTokenCols = personalAccessTokenColumns{
	ID:         sqlb.Typed[string]("id"),
	UserID:     sqlb.Typed[string]("user_id"),
	Name:       sqlb.TextColumn[string]("name"),
	TokenHash:  sqlb.TextColumn[string]("token_hash"),
	Scopes:     sqlb.ArrayColumn[string]("scopes"),
	ExpiresAt:  sqlb.Typed[time.Time]("expires_at"),
	LastUsedAt: sqlb.Typed[time.Time]("last_used_at"),
	RevokedAt:  sqlb.Typed[time.Time]("revoked_at"),
	CreatedAt:  sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:  sqlb.Typed[time.Time]("updated_at"),
}

// PersonalAccessTokenUpdate is a typed update statement for personal_access_tokens.
type PersonalAccessTokenUpdate struct {
	stmt *sqlb.Update[PersonalAccessToken]
}

// UpdatePersonalAccessToken starts a typed update.
func UpdatePersonalAccessToken() *PersonalAccessTokenUpdate {
	return &PersonalAccessTokenUpdate{stmt: sqlb.UpdateRows[PersonalAccessToken]()}
}

// SetUserID sets user_id.
func (u *PersonalAccessTokenUpdate) SetUserID(v string) *PersonalAccessTokenUpdate {
	u.stmt.Set("user_id", v)
	return u
}

// SetName sets name.
func (u *PersonalAccessTokenUpdate) SetName(v string) *PersonalAccessTokenUpdate {
	u.stmt.Set("name", v)
	return u
}

// SetTokenHash sets token_hash.
func (u *PersonalAccessTokenUpdate) SetTokenHash(v string) *PersonalAccessTokenUpdate {
	u.stmt.Set("token_hash", v)
	return u
}

// SetScopes sets scopes.
func (u *PersonalAccessTokenUpdate) SetScopes(v []string) *PersonalAccessTokenUpdate {
	u.stmt.Set("scopes", v)
	return u
}

// SetExpiresAt sets expires_at.
func (u *PersonalAccessTokenUpdate) SetExpiresAt(v *time.Time) *PersonalAccessTokenUpdate {
	u.stmt.Set("expires_at", v)
	return u
}

// SetLastUsedAt sets last_used_at.
func (u *PersonalAccessTokenUpdate) SetLastUsedAt(v *time.Time) *PersonalAccessTokenUpdate {
	u.stmt.Set("last_used_at", v)
	return u
}

// SetRevokedAt sets revoked_at.
func (u *PersonalAccessTokenUpdate) SetRevokedAt(v *time.Time) *PersonalAccessTokenUpdate {
	u.stmt.Set("revoked_at", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *PersonalAccessTokenUpdate) SetCreatedAt(v time.Time) *PersonalAccessTokenUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *PersonalAccessTokenUpdate) SetUpdatedAt(v time.Time) *PersonalAccessTokenUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *PersonalAccessTokenUpdate) Where(preds ...sqlb.Pred) *PersonalAccessTokenUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *PersonalAccessTokenUpdate) Stmt() *sqlb.Update[PersonalAccessToken] { return u.stmt }

type refreshTokenColumns struct {
	ID        sqlb.Col[string]
	UserID    sqlb.Col[string]
	TokenHash sqlb.TextCol[string]
	ExpiresAt sqlb.Col[time.Time]
	RevokedAt sqlb.Col[time.Time]
	UserAgent sqlb.TextCol[string]
	IPAddress sqlb.TextCol[string]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// RefreshTokenCols are the typed columns of refresh_tokens.
var RefreshTokenCols = refreshTokenColumns{
	ID:        sqlb.Typed[string]("id"),
	UserID:    sqlb.Typed[string]("user_id"),
	TokenHash: sqlb.TextColumn[string]("token_hash"),
	ExpiresAt: sqlb.Typed[time.Time]("expires_at"),
	RevokedAt: sqlb.Typed[time.Time]("revoked_at"),
	UserAgent: sqlb.TextColumn[string]("user_agent"),
	IPAddress: sqlb.TextColumn[string]("ip_address"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// RefreshTokenUpdate is a typed update statement for refresh_tokens.
type RefreshTokenUpdate struct {
	stmt *sqlb.Update[RefreshToken]
}

// UpdateRefreshToken starts a typed update.
func UpdateRefreshToken() *RefreshTokenUpdate {
	return &RefreshTokenUpdate{stmt: sqlb.UpdateRows[RefreshToken]()}
}

// SetUserID sets user_id.
func (u *RefreshTokenUpdate) SetUserID(v string) *RefreshTokenUpdate {
	u.stmt.Set("user_id", v)
	return u
}

// SetTokenHash sets token_hash.
func (u *RefreshTokenUpdate) SetTokenHash(v string) *RefreshTokenUpdate {
	u.stmt.Set("token_hash", v)
	return u
}

// SetExpiresAt sets expires_at.
func (u *RefreshTokenUpdate) SetExpiresAt(v time.Time) *RefreshTokenUpdate {
	u.stmt.Set("expires_at", v)
	return u
}

// SetRevokedAt sets revoked_at.
func (u *RefreshTokenUpdate) SetRevokedAt(v *time.Time) *RefreshTokenUpdate {
	u.stmt.Set("revoked_at", v)
	return u
}

// SetUserAgent sets user_agent.
func (u *RefreshTokenUpdate) SetUserAgent(v string) *RefreshTokenUpdate {
	u.stmt.Set("user_agent", v)
	return u
}

// SetIPAddress sets ip_address.
func (u *RefreshTokenUpdate) SetIPAddress(v string) *RefreshTokenUpdate {
	u.stmt.Set("ip_address", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *RefreshTokenUpdate) SetCreatedAt(v time.Time) *RefreshTokenUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *RefreshTokenUpdate) SetUpdatedAt(v time.Time) *RefreshTokenUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *RefreshTokenUpdate) Where(preds ...sqlb.Pred) *RefreshTokenUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *RefreshTokenUpdate) Stmt() *sqlb.Update[RefreshToken] { return u.stmt }

type superuserAccountLockColumns struct {
	SuperuserID sqlb.Col[string]
	LockedAt    sqlb.Col[time.Time]
}

// SuperuserAccountLockCols are the typed columns of superuser_account_locks.
var SuperuserAccountLockCols = superuserAccountLockColumns{
	SuperuserID: sqlb.Typed[string]("superuser_id"),
	LockedAt:    sqlb.Typed[time.Time]("locked_at"),
}

// SuperuserAccountLockUpdate is a typed update statement for superuser_account_locks.
type SuperuserAccountLockUpdate struct {
	stmt *sqlb.Update[SuperuserAccountLock]
}

// UpdateSuperuserAccountLock starts a typed update.
func UpdateSuperuserAccountLock() *SuperuserAccountLockUpdate {
	return &SuperuserAccountLockUpdate{stmt: sqlb.UpdateRows[SuperuserAccountLock]()}
}

// SetLockedAt sets locked_at.
func (u *SuperuserAccountLockUpdate) SetLockedAt(v time.Time) *SuperuserAccountLockUpdate {
	u.stmt.Set("locked_at", v)
	return u
}

// Where narrows the affected rows.
func (u *SuperuserAccountLockUpdate) Where(preds ...sqlb.Pred) *SuperuserAccountLockUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *SuperuserAccountLockUpdate) Stmt() *sqlb.Update[SuperuserAccountLock] { return u.stmt }

type superuserFailedLoginAttemptColumns struct {
	ID        sqlb.Col[string]
	Email     sqlb.TextCol[string]
	IPAddress sqlb.TextCol[string]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// SuperuserFailedLoginAttemptCols are the typed columns of superuser_failed_login_attempts.
var SuperuserFailedLoginAttemptCols = superuserFailedLoginAttemptColumns{
	ID:        sqlb.Typed[string]("id"),
	Email:     sqlb.TextColumn[string]("email"),
	IPAddress: sqlb.TextColumn[string]("ip_address"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// SuperuserFailedLoginAttemptUpdate is a typed update statement for superuser_failed_login_attempts.
type SuperuserFailedLoginAttemptUpdate struct {
	stmt *sqlb.Update[SuperuserFailedLoginAttempt]
}

// UpdateSuperuserFailedLoginAttempt starts a typed update.
func UpdateSuperuserFailedLoginAttempt() *SuperuserFailedLoginAttemptUpdate {
	return &SuperuserFailedLoginAttemptUpdate{stmt: sqlb.UpdateRows[SuperuserFailedLoginAttempt]()}
}

// SetEmail sets email.
func (u *SuperuserFailedLoginAttemptUpdate) SetEmail(v string) *SuperuserFailedLoginAttemptUpdate {
	u.stmt.Set("email", v)
	return u
}

// SetIPAddress sets ip_address.
func (u *SuperuserFailedLoginAttemptUpdate) SetIPAddress(v string) *SuperuserFailedLoginAttemptUpdate {
	u.stmt.Set("ip_address", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *SuperuserFailedLoginAttemptUpdate) SetCreatedAt(v time.Time) *SuperuserFailedLoginAttemptUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *SuperuserFailedLoginAttemptUpdate) SetUpdatedAt(v time.Time) *SuperuserFailedLoginAttemptUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *SuperuserFailedLoginAttemptUpdate) Where(preds ...sqlb.Pred) *SuperuserFailedLoginAttemptUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *SuperuserFailedLoginAttemptUpdate) Stmt() *sqlb.Update[SuperuserFailedLoginAttempt] {
	return u.stmt
}

type superuserRefreshTokenColumns struct {
	ID          sqlb.Col[string]
	SuperuserID sqlb.Col[string]
	TokenHash   sqlb.TextCol[string]
	ExpiresAt   sqlb.Col[time.Time]
	RevokedAt   sqlb.Col[time.Time]
	UserAgent   sqlb.TextCol[string]
	IPAddress   sqlb.TextCol[string]
	CreatedAt   sqlb.Col[time.Time]
	UpdatedAt   sqlb.Col[time.Time]
}

// SuperuserRefreshTokenCols are the typed columns of superuser_refresh_tokens.
var SuperuserRefreshTokenCols = superuserRefreshTokenColumns{
	ID:          sqlb.Typed[string]("id"),
	SuperuserID: sqlb.Typed[string]("superuser_id"),
	TokenHash:   sqlb.TextColumn[string]("token_hash"),
	ExpiresAt:   sqlb.Typed[time.Time]("expires_at"),
	RevokedAt:   sqlb.Typed[time.Time]("revoked_at"),
	UserAgent:   sqlb.TextColumn[string]("user_agent"),
	IPAddress:   sqlb.TextColumn[string]("ip_address"),
	CreatedAt:   sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:   sqlb.Typed[time.Time]("updated_at"),
}

// SuperuserRefreshTokenUpdate is a typed update statement for superuser_refresh_tokens.
type SuperuserRefreshTokenUpdate struct {
	stmt *sqlb.Update[SuperuserRefreshToken]
}

// UpdateSuperuserRefreshToken starts a typed update.
func UpdateSuperuserRefreshToken() *SuperuserRefreshTokenUpdate {
	return &SuperuserRefreshTokenUpdate{stmt: sqlb.UpdateRows[SuperuserRefreshToken]()}
}

// SetSuperuserID sets superuser_id.
func (u *SuperuserRefreshTokenUpdate) SetSuperuserID(v string) *SuperuserRefreshTokenUpdate {
	u.stmt.Set("superuser_id", v)
	return u
}

// SetTokenHash sets token_hash.
func (u *SuperuserRefreshTokenUpdate) SetTokenHash(v string) *SuperuserRefreshTokenUpdate {
	u.stmt.Set("token_hash", v)
	return u
}

// SetExpiresAt sets expires_at.
func (u *SuperuserRefreshTokenUpdate) SetExpiresAt(v time.Time) *SuperuserRefreshTokenUpdate {
	u.stmt.Set("expires_at", v)
	return u
}

// SetRevokedAt sets revoked_at.
func (u *SuperuserRefreshTokenUpdate) SetRevokedAt(v *time.Time) *SuperuserRefreshTokenUpdate {
	u.stmt.Set("revoked_at", v)
	return u
}

// SetUserAgent sets user_agent.
func (u *SuperuserRefreshTokenUpdate) SetUserAgent(v string) *SuperuserRefreshTokenUpdate {
	u.stmt.Set("user_agent", v)
	return u
}

// SetIPAddress sets ip_address.
func (u *SuperuserRefreshTokenUpdate) SetIPAddress(v string) *SuperuserRefreshTokenUpdate {
	u.stmt.Set("ip_address", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *SuperuserRefreshTokenUpdate) SetCreatedAt(v time.Time) *SuperuserRefreshTokenUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *SuperuserRefreshTokenUpdate) SetUpdatedAt(v time.Time) *SuperuserRefreshTokenUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *SuperuserRefreshTokenUpdate) Where(preds ...sqlb.Pred) *SuperuserRefreshTokenUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *SuperuserRefreshTokenUpdate) Stmt() *sqlb.Update[SuperuserRefreshToken] { return u.stmt }

type superuserColumns struct {
	ID           sqlb.Col[string]
	Email        sqlb.TextCol[string]
	PasswordHash sqlb.TextCol[string]
	DisplayName  sqlb.TextCol[string]
	IsActive     sqlb.Col[bool]
	LastLoginAt  sqlb.Col[time.Time]
	CreatedAt    sqlb.Col[time.Time]
	UpdatedAt    sqlb.Col[time.Time]
	CreatedByID  sqlb.Col[string]
}

// SuperuserCols are the typed columns of superusers.
var SuperuserCols = superuserColumns{
	ID:           sqlb.Typed[string]("id"),
	Email:        sqlb.TextColumn[string]("email"),
	PasswordHash: sqlb.TextColumn[string]("password_hash"),
	DisplayName:  sqlb.TextColumn[string]("display_name"),
	IsActive:     sqlb.Typed[bool]("is_active"),
	LastLoginAt:  sqlb.Typed[time.Time]("last_login_at"),
	CreatedAt:    sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:    sqlb.Typed[time.Time]("updated_at"),
	CreatedByID:  sqlb.Typed[string]("created_by_id"),
}

// SuperuserUpdate is a typed update statement for superusers.
type SuperuserUpdate struct {
	stmt *sqlb.Update[Superuser]
}

// UpdateSuperuser starts a typed update.
func UpdateSuperuser() *SuperuserUpdate {
	return &SuperuserUpdate{stmt: sqlb.UpdateRows[Superuser]()}
}

// SetEmail sets email.
func (u *SuperuserUpdate) SetEmail(v string) *SuperuserUpdate {
	u.stmt.Set("email", v)
	return u
}

// SetPasswordHash sets password_hash.
func (u *SuperuserUpdate) SetPasswordHash(v string) *SuperuserUpdate {
	u.stmt.Set("password_hash", v)
	return u
}

// SetDisplayName sets display_name.
func (u *SuperuserUpdate) SetDisplayName(v string) *SuperuserUpdate {
	u.stmt.Set("display_name", v)
	return u
}

// SetIsActive sets is_active.
func (u *SuperuserUpdate) SetIsActive(v bool) *SuperuserUpdate {
	u.stmt.Set("is_active", v)
	return u
}

// SetLastLoginAt sets last_login_at.
func (u *SuperuserUpdate) SetLastLoginAt(v *time.Time) *SuperuserUpdate {
	u.stmt.Set("last_login_at", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *SuperuserUpdate) SetCreatedAt(v time.Time) *SuperuserUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *SuperuserUpdate) SetUpdatedAt(v time.Time) *SuperuserUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// SetCreatedByID sets created_by_id.
func (u *SuperuserUpdate) SetCreatedByID(v *string) *SuperuserUpdate {
	u.stmt.Set("created_by_id", v)
	return u
}

// Where narrows the affected rows.
func (u *SuperuserUpdate) Where(preds ...sqlb.Pred) *SuperuserUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *SuperuserUpdate) Stmt() *sqlb.Update[Superuser] { return u.stmt }

type teamInvitationColumns struct {
	ID          sqlb.Col[string]
	TeamID      sqlb.Col[string]
	Email       sqlb.TextCol[string]
	TokenHash   sqlb.TextCol[string]
	Role        sqlb.TextCol[string]
	Status      sqlb.Col[TeamInvitationStatus]
	InvitedByID sqlb.Col[string]
	ExpiresAt   sqlb.Col[time.Time]
	AcceptedAt  sqlb.Col[time.Time]
	CreatedAt   sqlb.Col[time.Time]
	UpdatedAt   sqlb.Col[time.Time]
}

// TeamInvitationCols are the typed columns of team_invitations.
var TeamInvitationCols = teamInvitationColumns{
	ID:          sqlb.Typed[string]("id"),
	TeamID:      sqlb.Typed[string]("team_id"),
	Email:       sqlb.TextColumn[string]("email"),
	TokenHash:   sqlb.TextColumn[string]("token_hash"),
	Role:        sqlb.TextColumn[string]("role"),
	Status:      sqlb.Typed[TeamInvitationStatus]("status"),
	InvitedByID: sqlb.Typed[string]("invited_by_id"),
	ExpiresAt:   sqlb.Typed[time.Time]("expires_at"),
	AcceptedAt:  sqlb.Typed[time.Time]("accepted_at"),
	CreatedAt:   sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:   sqlb.Typed[time.Time]("updated_at"),
}

// TeamInvitationUpdate is a typed update statement for team_invitations.
type TeamInvitationUpdate struct {
	stmt *sqlb.Update[TeamInvitation]
}

// UpdateTeamInvitation starts a typed update.
func UpdateTeamInvitation() *TeamInvitationUpdate {
	return &TeamInvitationUpdate{stmt: sqlb.UpdateRows[TeamInvitation]()}
}

// SetTeamID sets team_id.
func (u *TeamInvitationUpdate) SetTeamID(v string) *TeamInvitationUpdate {
	u.stmt.Set("team_id", v)
	return u
}

// SetEmail sets email.
func (u *TeamInvitationUpdate) SetEmail(v string) *TeamInvitationUpdate {
	u.stmt.Set("email", v)
	return u
}

// SetTokenHash sets token_hash.
func (u *TeamInvitationUpdate) SetTokenHash(v string) *TeamInvitationUpdate {
	u.stmt.Set("token_hash", v)
	return u
}

// SetRole sets role.
func (u *TeamInvitationUpdate) SetRole(v string) *TeamInvitationUpdate {
	u.stmt.Set("role", v)
	return u
}

// SetStatus sets status.
func (u *TeamInvitationUpdate) SetStatus(v TeamInvitationStatus) *TeamInvitationUpdate {
	u.stmt.Set("status", v)
	return u
}

// SetInvitedByID sets invited_by_id.
func (u *TeamInvitationUpdate) SetInvitedByID(v string) *TeamInvitationUpdate {
	u.stmt.Set("invited_by_id", v)
	return u
}

// SetExpiresAt sets expires_at.
func (u *TeamInvitationUpdate) SetExpiresAt(v time.Time) *TeamInvitationUpdate {
	u.stmt.Set("expires_at", v)
	return u
}

// SetAcceptedAt sets accepted_at.
func (u *TeamInvitationUpdate) SetAcceptedAt(v *time.Time) *TeamInvitationUpdate {
	u.stmt.Set("accepted_at", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *TeamInvitationUpdate) SetCreatedAt(v time.Time) *TeamInvitationUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *TeamInvitationUpdate) SetUpdatedAt(v time.Time) *TeamInvitationUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *TeamInvitationUpdate) Where(preds ...sqlb.Pred) *TeamInvitationUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *TeamInvitationUpdate) Stmt() *sqlb.Update[TeamInvitation] { return u.stmt }

type teamMemberColumns struct {
	ID          sqlb.Col[string]
	TeamID      sqlb.Col[string]
	UserID      sqlb.Col[string]
	Role        sqlb.TextCol[string]
	DisplayName sqlb.TextCol[string]
	Email       sqlb.TextCol[string]
	IsActive    sqlb.Col[bool]
	CreatedAt   sqlb.Col[time.Time]
	UpdatedAt   sqlb.Col[time.Time]
}

// TeamMemberCols are the typed columns of team_members.
var TeamMemberCols = teamMemberColumns{
	ID:          sqlb.Typed[string]("id"),
	TeamID:      sqlb.Typed[string]("team_id"),
	UserID:      sqlb.Typed[string]("user_id"),
	Role:        sqlb.TextColumn[string]("role"),
	DisplayName: sqlb.TextColumn[string]("display_name"),
	Email:       sqlb.TextColumn[string]("email"),
	IsActive:    sqlb.Typed[bool]("is_active"),
	CreatedAt:   sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:   sqlb.Typed[time.Time]("updated_at"),
}

// TeamMemberUpdate is a typed update statement for team_members.
type TeamMemberUpdate struct {
	stmt *sqlb.Update[TeamMember]
}

// UpdateTeamMember starts a typed update.
func UpdateTeamMember() *TeamMemberUpdate {
	return &TeamMemberUpdate{stmt: sqlb.UpdateRows[TeamMember]()}
}

// SetTeamID sets team_id.
func (u *TeamMemberUpdate) SetTeamID(v string) *TeamMemberUpdate {
	u.stmt.Set("team_id", v)
	return u
}

// SetUserID sets user_id.
func (u *TeamMemberUpdate) SetUserID(v *string) *TeamMemberUpdate {
	u.stmt.Set("user_id", v)
	return u
}

// SetRole sets role.
func (u *TeamMemberUpdate) SetRole(v string) *TeamMemberUpdate {
	u.stmt.Set("role", v)
	return u
}

// SetDisplayName sets display_name.
func (u *TeamMemberUpdate) SetDisplayName(v string) *TeamMemberUpdate {
	u.stmt.Set("display_name", v)
	return u
}

// SetEmail sets email.
func (u *TeamMemberUpdate) SetEmail(v string) *TeamMemberUpdate {
	u.stmt.Set("email", v)
	return u
}

// SetIsActive sets is_active.
func (u *TeamMemberUpdate) SetIsActive(v bool) *TeamMemberUpdate {
	u.stmt.Set("is_active", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *TeamMemberUpdate) SetCreatedAt(v time.Time) *TeamMemberUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *TeamMemberUpdate) SetUpdatedAt(v time.Time) *TeamMemberUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *TeamMemberUpdate) Where(preds ...sqlb.Pred) *TeamMemberUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *TeamMemberUpdate) Stmt() *sqlb.Update[TeamMember] { return u.stmt }

type teamColumns struct {
	ID        sqlb.Col[string]
	Name      sqlb.TextCol[string]
	Slug      sqlb.TextCol[string]
	OwnerID   sqlb.Col[string]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// TeamCols are the typed columns of teams.
var TeamCols = teamColumns{
	ID:        sqlb.Typed[string]("id"),
	Name:      sqlb.TextColumn[string]("name"),
	Slug:      sqlb.TextColumn[string]("slug"),
	OwnerID:   sqlb.Typed[string]("owner_id"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// TeamUpdate is a typed update statement for teams.
type TeamUpdate struct {
	stmt *sqlb.Update[Team]
}

// UpdateTeam starts a typed update.
func UpdateTeam() *TeamUpdate {
	return &TeamUpdate{stmt: sqlb.UpdateRows[Team]()}
}

// SetName sets name.
func (u *TeamUpdate) SetName(v string) *TeamUpdate {
	u.stmt.Set("name", v)
	return u
}

// SetSlug sets slug.
func (u *TeamUpdate) SetSlug(v string) *TeamUpdate {
	u.stmt.Set("slug", v)
	return u
}

// SetOwnerID sets owner_id.
func (u *TeamUpdate) SetOwnerID(v string) *TeamUpdate {
	u.stmt.Set("owner_id", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *TeamUpdate) SetCreatedAt(v time.Time) *TeamUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *TeamUpdate) SetUpdatedAt(v time.Time) *TeamUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *TeamUpdate) Where(preds ...sqlb.Pred) *TeamUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *TeamUpdate) Stmt() *sqlb.Update[Team] { return u.stmt }

type totpSettingColumns struct {
	ID                 sqlb.Col[string]
	UserID             sqlb.Col[string]
	SecretEncrypted    sqlb.Col[[]byte]
	Enabled            sqlb.Col[bool]
	VerifiedAt         sqlb.Col[time.Time]
	RecoveryCodeHashes sqlb.ArrayCol[string]
	RecoveryCodesUsed  sqlb.Col[int32]
	CreatedAt          sqlb.Col[time.Time]
	UpdatedAt          sqlb.Col[time.Time]
}

// TotpSettingCols are the typed columns of totp_settings.
var TotpSettingCols = totpSettingColumns{
	ID:                 sqlb.Typed[string]("id"),
	UserID:             sqlb.Typed[string]("user_id"),
	SecretEncrypted:    sqlb.Typed[[]byte]("secret_encrypted"),
	Enabled:            sqlb.Typed[bool]("enabled"),
	VerifiedAt:         sqlb.Typed[time.Time]("verified_at"),
	RecoveryCodeHashes: sqlb.ArrayColumn[string]("recovery_code_hashes"),
	RecoveryCodesUsed:  sqlb.Typed[int32]("recovery_codes_used"),
	CreatedAt:          sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:          sqlb.Typed[time.Time]("updated_at"),
}

// TotpSettingUpdate is a typed update statement for totp_settings.
type TotpSettingUpdate struct {
	stmt *sqlb.Update[TotpSetting]
}

// UpdateTotpSetting starts a typed update.
func UpdateTotpSetting() *TotpSettingUpdate {
	return &TotpSettingUpdate{stmt: sqlb.UpdateRows[TotpSetting]()}
}

// SetUserID sets user_id.
func (u *TotpSettingUpdate) SetUserID(v string) *TotpSettingUpdate {
	u.stmt.Set("user_id", v)
	return u
}

// SetSecretEncrypted sets secret_encrypted.
func (u *TotpSettingUpdate) SetSecretEncrypted(v []byte) *TotpSettingUpdate {
	u.stmt.Set("secret_encrypted", v)
	return u
}

// SetEnabled sets enabled.
func (u *TotpSettingUpdate) SetEnabled(v bool) *TotpSettingUpdate {
	u.stmt.Set("enabled", v)
	return u
}

// SetVerifiedAt sets verified_at.
func (u *TotpSettingUpdate) SetVerifiedAt(v *time.Time) *TotpSettingUpdate {
	u.stmt.Set("verified_at", v)
	return u
}

// SetRecoveryCodeHashes sets recovery_code_hashes.
func (u *TotpSettingUpdate) SetRecoveryCodeHashes(v []string) *TotpSettingUpdate {
	u.stmt.Set("recovery_code_hashes", v)
	return u
}

// SetRecoveryCodesUsed sets recovery_codes_used.
func (u *TotpSettingUpdate) SetRecoveryCodesUsed(v int32) *TotpSettingUpdate {
	u.stmt.Set("recovery_codes_used", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *TotpSettingUpdate) SetCreatedAt(v time.Time) *TotpSettingUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *TotpSettingUpdate) SetUpdatedAt(v time.Time) *TotpSettingUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *TotpSettingUpdate) Where(preds ...sqlb.Pred) *TotpSettingUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *TotpSettingUpdate) Stmt() *sqlb.Update[TotpSetting] { return u.stmt }

type userColumns struct {
	ID              sqlb.Col[string]
	Email           sqlb.TextCol[string]
	PasswordHash    sqlb.TextCol[string]
	EmailVerified   sqlb.Col[bool]
	EmailVerifiedAt sqlb.Col[time.Time]
	CreatedAt       sqlb.Col[time.Time]
	UpdatedAt       sqlb.Col[time.Time]
}

// UserCols are the typed columns of users.
var UserCols = userColumns{
	ID:              sqlb.Typed[string]("id"),
	Email:           sqlb.TextColumn[string]("email"),
	PasswordHash:    sqlb.TextColumn[string]("password_hash"),
	EmailVerified:   sqlb.Typed[bool]("email_verified"),
	EmailVerifiedAt: sqlb.Typed[time.Time]("email_verified_at"),
	CreatedAt:       sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:       sqlb.Typed[time.Time]("updated_at"),
}

// UserUpdate is a typed update statement for users.
type UserUpdate struct {
	stmt *sqlb.Update[User]
}

// UpdateUser starts a typed update.
func UpdateUser() *UserUpdate {
	return &UserUpdate{stmt: sqlb.UpdateRows[User]()}
}

// SetEmail sets email.
func (u *UserUpdate) SetEmail(v string) *UserUpdate {
	u.stmt.Set("email", v)
	return u
}

// SetPasswordHash sets password_hash.
func (u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	u.stmt.Set("password_hash", v)
	return u
}

// SetEmailVerified sets email_verified.
func (u *UserUpdate) SetEmailVerified(v bool) *UserUpdate {
	u.stmt.Set("email_verified", v)
	return u
}

// SetEmailVerifiedAt sets email_verified_at.
func (u *UserUpdate) SetEmailVerifiedAt(v *time.Time) *UserUpdate {
	u.stmt.Set("email_verified_at", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *UserUpdate) SetCreatedAt(v time.Time) *UserUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *UserUpdate) Where(preds ...sqlb.Pred) *UserUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *UserUpdate) Stmt() *sqlb.Update[User] { return u.stmt }
