// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.

package store

import "time"

// AccountLock the set of currently locked-out accounts.
type AccountLock struct {
	UserID   string    `db:"user_id" json:"user_id" sqlb:"type:uuid,pk,filter,readonly"`
	LockedAt time.Time `db:"locked_at" json:"locked_at" sqlb:"type:timestamptz,default"`
}

// TableName is the table AccountLock maps to.
func (AccountLock) TableName() string { return "account_locks" }

// DeviceAuthorizationStatus is the device_authorizations.status column's value set.
type DeviceAuthorizationStatus string

const (
	DeviceAuthorizationStatusPending  DeviceAuthorizationStatus = "pending"
	DeviceAuthorizationStatusApproved DeviceAuthorizationStatus = "approved"
	DeviceAuthorizationStatusDenied   DeviceAuthorizationStatus = "denied"
)

// DeviceAuthorization an in-flight device authorization grant.
type DeviceAuthorization struct {
	ID              string                    `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	DeviceCodeHash  string                    `db:"device_code_hash" json:"device_code_hash" sqlb:"type:text"`
	UserCode        string                    `db:"user_code" json:"user_code" sqlb:"type:text"`
	ClientID        string                    `db:"client_id" json:"client_id" sqlb:"type:text,default"`
	Scope           string                    `db:"scope" json:"scope" sqlb:"type:text,default"`
	Status          DeviceAuthorizationStatus `db:"status" json:"status" sqlb:"type:enum,default"`
	UserID          *string                   `db:"user_id" json:"user_id" sqlb:"type:uuid"`
	ExpiresAt       time.Time                 `db:"expires_at" json:"expires_at" sqlb:"type:timestamptz"`
	IntervalSeconds int32                     `db:"interval_seconds" json:"interval_seconds" sqlb:"type:int"`
	LastPolledAt    *time.Time                `db:"last_polled_at" json:"last_polled_at" sqlb:"type:timestamptz"`
	CreatedAt       time.Time                 `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt       time.Time                 `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table DeviceAuthorization maps to.
func (DeviceAuthorization) TableName() string { return "device_authorizations" }

// EmailVerificationToken a single-use email verification token. Only its hash is stored.
type EmailVerificationToken struct {
	ID        string     `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	UserID    string     `db:"user_id" json:"user_id" sqlb:"type:uuid"`
	TokenHash string     `db:"token_hash" json:"token_hash" sqlb:"type:text"`
	ExpiresAt time.Time  `db:"expires_at" json:"expires_at" sqlb:"type:timestamptz"`
	UsedAt    *time.Time `db:"used_at" json:"used_at" sqlb:"type:timestamptz"`
	CreatedAt time.Time  `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt time.Time  `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table EmailVerificationToken maps to.
func (EmailVerificationToken) TableName() string { return "email_verification_tokens" }

// FailedLoginAttempt one failed login, keyed by email so lockout can't leak account existence.
type FailedLoginAttempt struct {
	ID        string    `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	Email     string    `db:"email" json:"email" sqlb:"type:text"`
	IPAddress string    `db:"ip_address" json:"ip_address" sqlb:"type:text,default"`
	CreatedAt time.Time `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table FailedLoginAttempt maps to.
func (FailedLoginAttempt) TableName() string { return "failed_login_attempts" }

// PasswordResetToken a single-use password reset token. Only its hash is stored.
type PasswordResetToken struct {
	ID        string     `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	UserID    string     `db:"user_id" json:"user_id" sqlb:"type:uuid"`
	TokenHash string     `db:"token_hash" json:"token_hash" sqlb:"type:text"`
	ExpiresAt time.Time  `db:"expires_at" json:"expires_at" sqlb:"type:timestamptz"`
	UsedAt    *time.Time `db:"used_at" json:"used_at" sqlb:"type:timestamptz"`
	CreatedAt time.Time  `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt time.Time  `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table PasswordResetToken maps to.
func (PasswordResetToken) TableName() string { return "password_reset_tokens" }

// PendingTwoFactorSession a short-lived session awaiting its second factor.
type PendingTwoFactorSession struct {
	ID        string    `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	UserID    string    `db:"user_id" json:"user_id" sqlb:"type:uuid"`
	TokenHash string    `db:"token_hash" json:"token_hash" sqlb:"type:text"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at" sqlb:"type:timestamptz"`
	CreatedAt time.Time `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table PendingTwoFactorSession maps to.
func (PendingTwoFactorSession) TableName() string { return "pending_two_factor_sessions" }

// PersonalAccessToken a named, scoped, long-lived bearer credential for a CLI or script.
type PersonalAccessToken struct {
	ID         string     `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	UserID     string     `db:"user_id" json:"user_id" sqlb:"type:uuid"`
	Name       string     `db:"name" json:"name" sqlb:"type:text,default"`
	TokenHash  string     `db:"token_hash" json:"token_hash" sqlb:"type:text"`
	Scopes     []string   `db:"scopes" json:"scopes" sqlb:"type:text,default"`
	ExpiresAt  *time.Time `db:"expires_at" json:"expires_at" sqlb:"type:timestamptz"`
	LastUsedAt *time.Time `db:"last_used_at" json:"last_used_at" sqlb:"type:timestamptz"`
	RevokedAt  *time.Time `db:"revoked_at" json:"revoked_at" sqlb:"type:timestamptz"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt  time.Time  `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table PersonalAccessToken maps to.
func (PersonalAccessToken) TableName() string { return "personal_access_tokens" }

// RefreshToken a server-side session. Only the token's hash is stored.
type RefreshToken struct {
	ID        string     `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	UserID    string     `db:"user_id" json:"user_id" sqlb:"type:uuid"`
	TokenHash string     `db:"token_hash" json:"token_hash" sqlb:"type:text"`
	ExpiresAt time.Time  `db:"expires_at" json:"expires_at" sqlb:"type:timestamptz"`
	RevokedAt *time.Time `db:"revoked_at" json:"revoked_at" sqlb:"type:timestamptz"`
	UserAgent string     `db:"user_agent" json:"user_agent" sqlb:"type:text,default"`
	IPAddress string     `db:"ip_address" json:"ip_address" sqlb:"type:text,default"`
	CreatedAt time.Time  `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt time.Time  `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table RefreshToken maps to.
func (RefreshToken) TableName() string { return "refresh_tokens" }

// SuperuserAccountLock the set of currently locked-out operator accounts.
type SuperuserAccountLock struct {
	SuperuserID string    `db:"superuser_id" json:"superuser_id" sqlb:"type:uuid,pk,filter,readonly"`
	LockedAt    time.Time `db:"locked_at" json:"locked_at" sqlb:"type:timestamptz,default"`
}

// TableName is the table SuperuserAccountLock maps to.
func (SuperuserAccountLock) TableName() string { return "superuser_account_locks" }

// SuperuserFailedLoginAttempt one failed operator login, keyed by email.
type SuperuserFailedLoginAttempt struct {
	ID        string    `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	Email     string    `db:"email" json:"email" sqlb:"type:text"`
	IPAddress string    `db:"ip_address" json:"ip_address" sqlb:"type:text,default"`
	CreatedAt time.Time `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table SuperuserFailedLoginAttempt maps to.
func (SuperuserFailedLoginAttempt) TableName() string { return "superuser_failed_login_attempts" }

// SuperuserRefreshToken an operator session. Kept apart from user sessions on purpose.
type SuperuserRefreshToken struct {
	ID          string     `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	SuperuserID string     `db:"superuser_id" json:"superuser_id" sqlb:"type:uuid"`
	TokenHash   string     `db:"token_hash" json:"token_hash" sqlb:"type:text"`
	ExpiresAt   time.Time  `db:"expires_at" json:"expires_at" sqlb:"type:timestamptz"`
	RevokedAt   *time.Time `db:"revoked_at" json:"revoked_at" sqlb:"type:timestamptz"`
	UserAgent   string     `db:"user_agent" json:"user_agent" sqlb:"type:text,default"`
	IPAddress   string     `db:"ip_address" json:"ip_address" sqlb:"type:text,default"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table SuperuserRefreshToken maps to.
func (SuperuserRefreshToken) TableName() string { return "superuser_refresh_tokens" }

// Superuser an operator identity, structurally separate from users.
type Superuser struct {
	ID           string     `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	Email        string     `db:"email" json:"email" sqlb:"type:text"`
	PasswordHash string     `db:"password_hash" json:"-" sqlb:"type:text,writeonly"`
	DisplayName  string     `db:"display_name" json:"display_name" sqlb:"type:text,default"`
	IsActive     bool       `db:"is_active" json:"is_active" sqlb:"type:bool,default"`
	LastLoginAt  *time.Time `db:"last_login_at" json:"last_login_at" sqlb:"type:timestamptz"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt    time.Time  `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
	CreatedByID  *string    `db:"created_by_id" json:"created_by_id" sqlb:"type:uuid"`
}

// TableName is the table Superuser maps to.
func (Superuser) TableName() string { return "superusers" }

// TeamInvitationStatus is the team_invitations.status column's value set.
type TeamInvitationStatus string

const (
	TeamInvitationStatusPending  TeamInvitationStatus = "pending"
	TeamInvitationStatusAccepted TeamInvitationStatus = "accepted"
	TeamInvitationStatusRevoked  TeamInvitationStatus = "revoked"
)

// TeamInvitation an offer for an address to join a team. Only the token's hash is stored.
type TeamInvitation struct {
	ID          string               `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	TeamID      string               `db:"team_id" json:"team_id" sqlb:"type:uuid"`
	Email       string               `db:"email" json:"email" sqlb:"type:text"`
	TokenHash   string               `db:"token_hash" json:"token_hash" sqlb:"type:text"`
	Role        string               `db:"role" json:"role" sqlb:"type:text"`
	Status      TeamInvitationStatus `db:"status" json:"status" sqlb:"type:enum,default"`
	InvitedByID string               `db:"invited_by_id" json:"invited_by_id" sqlb:"type:uuid"`
	ExpiresAt   time.Time            `db:"expires_at" json:"expires_at" sqlb:"type:timestamptz"`
	AcceptedAt  *time.Time           `db:"accepted_at" json:"accepted_at" sqlb:"type:timestamptz"`
	CreatedAt   time.Time            `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt   time.Time            `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table TeamInvitation maps to.
func (TeamInvitation) TableName() string { return "team_invitations" }

// TeamMember a user's membership of a team, and their role in it.
type TeamMember struct {
	ID          string    `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	TeamID      string    `db:"team_id" json:"team_id" sqlb:"type:uuid"`
	UserID      *string   `db:"user_id" json:"user_id" sqlb:"type:uuid"`
	Role        string    `db:"role" json:"role" sqlb:"type:text"`
	DisplayName string    `db:"display_name" json:"display_name" sqlb:"type:text,default"`
	Email       string    `db:"email" json:"email" sqlb:"type:text,default"`
	IsActive    bool      `db:"is_active" json:"is_active" sqlb:"type:bool,default"`
	CreatedAt   time.Time `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table TeamMember maps to.
func (TeamMember) TableName() string { return "team_members" }

// Team an organization users belong to via a membership.
type Team struct {
	ID        string    `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	Name      string    `db:"name" json:"name" sqlb:"type:text"`
	Slug      string    `db:"slug" json:"slug" sqlb:"type:text"`
	OwnerID   string    `db:"owner_id" json:"owner_id" sqlb:"type:uuid"`
	CreatedAt time.Time `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table Team maps to.
func (Team) TableName() string { return "teams" }

// TotpSetting a user's TOTP enrollment and hashed backup codes.
type TotpSetting struct {
	ID                 string     `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	UserID             string     `db:"user_id" json:"user_id" sqlb:"type:uuid"`
	SecretEncrypted    []byte     `db:"secret_encrypted" json:"-" sqlb:"type:bytea,writeonly"`
	Enabled            bool       `db:"enabled" json:"enabled" sqlb:"type:bool,default"`
	VerifiedAt         *time.Time `db:"verified_at" json:"verified_at" sqlb:"type:timestamptz"`
	RecoveryCodeHashes []string   `db:"recovery_code_hashes" json:"-" sqlb:"type:text,default,writeonly"`
	RecoveryCodesUsed  int32      `db:"recovery_codes_used" json:"recovery_codes_used" sqlb:"type:int,default"`
	CreatedAt          time.Time  `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt          time.Time  `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table TotpSetting maps to.
func (TotpSetting) TableName() string { return "totp_settings" }

// User a login-capable identity. Profile data joins by id.
type User struct {
	ID              string     `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	Email           string     `db:"email" json:"email" sqlb:"type:text"`
	PasswordHash    string     `db:"password_hash" json:"-" sqlb:"type:text,writeonly"`
	EmailVerified   bool       `db:"email_verified" json:"email_verified" sqlb:"type:bool,default"`
	EmailVerifiedAt *time.Time `db:"email_verified_at" json:"email_verified_at" sqlb:"type:timestamptz"`
	CreatedAt       time.Time  `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt       time.Time  `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table User maps to.
func (User) TableName() string { return "users" }
